micronaut:
  application:
    name: fluxshare
  server:
    max-request-size: 128MB
logger:
  levels:
    com.tranxfer: DEBUG
    io.micronaut.security: DEBUG
    io.micronaut.http: DEBUG
    io.reactor: DEBUG
